spring.application.name=ms-oc
server.port=8082

spring.datasource.url=jdbc:oracle:thin:@//37.187.250.163:1521/ORCLPDB1
spring.datasource.username=MSOC
spring.datasource.password=MSOC
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=ms-oc-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

msoc.kafka.inbound-topic=station.oc.inbound
msoc.kafka.outbound-topic=oc.station.outbound
msoc.outbox.fixed-delay-ms=5000
msoc.outbox.batch-size=50

security.jwt.secret=CHANGE_ME_CHANGE_ME_CHANGE_ME_CHANGE_ME_32_CHARS_MIN
spring.profiles.active=dev
