spring.application.name=ms-oc
server.port=8082

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.locations=classpath:db/migration

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

msoc.kafka.inbound-topic=station.oc.inbound
msoc.kafka.outbound-topic=oc.station.outbound
msoc.outbox.fixed-delay-ms=5000
msoc.outbox.batch-size=50

security.jwt.secret=JcIdM7U+Q3Bp1L+BBlUmg3nQh+v60jKejqr1H64EyakcW6TzFeOrIa4is8AcHeaQC4R5TglzKiEQtsVAoYPKmdot9EgxBugTxhYBrEf2qfMZupXCMG8Rb4BLvr8hyiX7YrjJoN/ZhJACGoyqF1HquBWTTHmqFSmMWPmuqatVCzA+knyWsUdXkzR1FS3SFjNmFpAp4VgInet1NKb+MU1wdE9Bpd1r67EZwWSGilD3N3bZBF2tteUVqeC+X5uRQttAqlsqxFEu0/CL0qggISaUJTz/g7pz/fXYvEpQTJI+XMcOxSeJPLpdv+4ax+jW7qCW35wrrledqN/cZ6E1XwyNOyYdFu5+jrT6y7zxvFSu1qo=

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.jackson.serialization.write-dates-as-timestamps=false

spring.profiles.active=dev

app.log.dir=logs