spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.enabled=false

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=ms-oc-consumer-prod
spring.kafka.consumer.auto-offset-reset=latest

logging.level.com.banque.msoc=INFO
logging.level.org.hibernate.SQL=ERROR

security.jwt.secret=${JWT_SECRET}

#$env:SPRING_PROFILES_ACTIVE="prod"
#$env:DB_URL="jdbc:oracle:thin:@//37.187.250.163:1521/ORCLPDB1"
#$env:DB_USERNAME="MSOC"
#$env:DB_PASSWORD="MSOC"
#$env:JWT_SECRET="ton_secret_jwt_prod"
#$env:KAFKA_BOOTSTRAP_SERVERS="localhost:9092"
#java -jar ms-oc.jar